inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  TargetRailsVersion: 4.1
  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'db/migrate/*'

Rails:
  Enabled: true

Style/Encoding:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  # After a long discussion we agreed that a long method is not a problem. The actual problem are methods with too much
  # logic within that should be split into tinier units. No tool can measure that but a programmer's brain.
  Enabled: false

Metrics/BlockLength:
  # We disable this cop for the same reason we disabled Metrics/MethodLength
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 130

Metrics/ModuleLength:
  Max: 120
